language: python

matrix:
  fast_finish: true
  include:
    - python: pypy
    - python: pypy3
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: 3.3
    - python: 2.7
    - python: 2.6

sudo: false

install:
 # Workaround https://github.com/tweepy/tweepy/issues/1063
 - if [[ $TRAVIS_PYTHON_VERSION != 3.7 ]]; then pip install tweepy; fi
 - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install -U git+https://github.com/tweepy/tweepy.git; fi

 - pip install coverage

script:
 - coverage run --source=everywordbot test/test_everywordbot.py -v

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pep8 pyflakes
 - pep8 --statistics --count .
 - pyflakes . | tee >(wc -l)
