language: python

python:
 - pypy
 - pypy3
 - 2.7
 - 3.6
 - 3.5
 - 3.4
 - 3.3
 - 2.6

sudo: false

install:
 - pip install coverage tweepy

script:
 - coverage run --source=everywordbot test/test_everywordbot.py -v

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pep8 pyflakes
 - pep8 --statistics --count .
 - pyflakes . | tee >(wc -l)

matrix:
  fast_finish: true
